# Generated by Django 4.1 on 2022-10-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofilelogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
