# Generated by Django 4.1 on 2022-09-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], default='SELECT', max_length=20),
        ),
    ]
