# Generated by Django 4.1 on 2022-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Mandate', 'Mandate')], default='SELECT', max_length=20),
        ),
    ]
