# Generated by Django 4.1 on 2022-10-24 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default=1, upload_to='customer'),
            preserve_default=False,
        ),
    ]
