# Generated by Django 4.1 on 2022-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(upload_to='customer/'),
        ),
    ]
