# Generated by Django 4.1 on 2022-11-12 13:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_origin',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
