# Generated by Django 4.1 on 2022-12-11 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_customer_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
