# Generated by Django 4.1 on 2023-01-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='customer/', upload_to='customer/'),
        ),
    ]
