# Generated by Django 4.1 on 2022-10-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('company_info', models.TextField()),
                ('mission', models.CharField(max_length=250)),
                ('mission_description', models.TextField()),
                ('vision', models.CharField(max_length=250)),
                ('vision_description', models.TextField()),
            ],
        ),
    ]
