# Generated by Django 4.1 on 2022-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='company',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.CharField(max_length=1000),
        ),
    ]
