# Generated by Django 4.1 on 2022-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactus_alter_aboutus_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
