# Generated by Django 4.1 on 2022-10-24 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_contactusfrontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusfrontend',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
