# Generated by Django 4.1 on 2022-12-10 13:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_contactusfrontend_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
