# Generated by Django 4.1 on 2022-10-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.FileField(upload_to='blog/'),
        ),
    ]
