# Generated by Django 4.1 on 2022-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.FileField(default='blog/images/', upload_to='blog/'),
        ),
    ]
