# Generated by Django 4.1 on 2022-09-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_productprice'),
        ('customer', '0002_alter_customer_customer_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyShareToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_quantity', models.CharField(max_length=100)),
                ('share_pricing', models.CharField(max_length=10)),
                ('buyer_share_tax', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('share_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
