# Generated by Django 4.1 on 2022-11-12 14:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
