# Generated by Django 4.1 on 2022-11-12 15:02

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_policy_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='content',
        ),
        migrations.AddField(
            model_name='policy',
            name='contents',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
