# Generated by Django 4.1 on 2022-11-12 16:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_policy_content_policy_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('contents', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='policy',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
