# Generated by Django 4.1 on 2022-12-10 13:39

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_termcondition_alter_policy_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='contents',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termcondition',
            name='contents',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termcondition',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
