# Generated by Django 4.1 on 2022-10-23 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
