# Generated by Django 4.1 on 2022-10-24 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productprice_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=1000),
        ),
    ]
