# Generated by Django 4.1 on 2022-12-10 13:39

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0008_alter_customer_customer_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('SELECT', 'SELECT'), ('Activated Account', 'Activated Account'), ('Reset Password', 'Reset Password'), ('Commission', 'Commission'), ('Others', 'Others')], default='SELECT', max_length=20)),
                ('document', models.FileField(upload_to='dms')),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
