# Generated by Django 4.1 on 2022-12-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmanagementsystem',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
