# Generated by Django 4.1 on 2022-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0002_rename_end_data_documentmanagementsystem_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagementsystem',
            name='dms_status',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Padding', 'Padding'), ('Others', 'Others')], default='SELECT', max_length=20),
        ),
    ]
