# Generated by Django 4.1 on 2022-12-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_customer_origin'),
        ('DMS', '0003_documentmanagementsystem_dms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmanagementsystem',
            name='document',
            field=models.ImageField(upload_to='dms'),
        ),
        migrations.AlterField(
            model_name='documentmanagementsystem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
